import type { RawLogEntryRecord } from "../domain/types.js";

const baseResource = {
  type: "cloud_run_revision",
  labels: {
    project_id: "sample-project",
    service_name: "mcp-agent8",
    revision_name: "mcp-agent8-00012-sample",
    location: "asia-northeast3",
  },
};

export const sampleEntries: RawLogEntryRecord[] = [
  {
    id: "sample-1",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:00.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet generation requested",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      provider: "google",
      model: "imagen-4",
      phase: "request",
      rows: 4,
      cols: 4,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-2",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:01.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Provider request started",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      provider: "google",
      model: "imagen-4",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-3",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:19.800Z",
    severity: "INFO",
    jsonPayload: {
      message: "Provider request completed",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      provider: "google",
      durationMs: 19800,
      totalDurationMs: 19800,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-4",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:26.700Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet analysis completed",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      durationMs: 6900,
      totalDurationMs: 26700,
      rows: 4,
      cols: 4,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-5",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:26.950Z",
    severity: "INFO",
    jsonPayload: {
      message: "Background removal completed",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      phase: "post_processing",
      durationMs: 120,
      totalDurationMs: 26950,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-6",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:28.900Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet upload completed",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      phase: "upload",
      durationMs: 2000,
      totalDurationMs: 28900,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-7",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T09:00:28.950Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet generation completed",
      toolFlow: "spritesheet_generate",
      operationId: "sprite-op-001",
      phase: "completed",
      totalDurationMs: 28900,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-8",
    logName: "projects/sample-project/logs/stderr",
    timestamp: "2026-03-11T10:15:00.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Image generation requested",
      toolFlow: "image_asset_generate",
      operationId: "image-op-002",
      provider: "google",
      model: "imagen-4",
      phase: "request",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-9",
    logName: "projects/sample-project/logs/stderr",
    timestamp: "2026-03-11T10:15:02.500Z",
    severity: "WARNING",
    jsonPayload: {
      message: "Primary model failed; starting fallback",
      toolFlow: "image_asset_generate",
      operationId: "image-op-002",
      provider: "fal",
      phase: "fallback",
      fallbackFromModel: "imagen-4",
      totalDurationMs: 2500,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-10",
    logName: "projects/sample-project/logs/stderr",
    timestamp: "2026-03-11T10:15:02.700Z",
    severity: "INFO",
    jsonPayload: {
      message: "fal generation started",
      toolFlow: "image_asset_generate",
      operationId: "image-op-002",
      requestId: "fal-req-002",
      provider: "fal",
      phase: "provider_request",
      modelPath: "fal-ai/fast-sdxl",
      totalDurationMs: 2700,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-11",
    logName: "projects/sample-project/logs/stderr",
    timestamp: "2026-03-11T10:15:03.200Z",
    severity: "INFO",
    jsonPayload: {
      message: "fal queue accepted",
      toolFlow: "image_asset_generate",
      operationId: "image-op-002",
      requestId: "fal-req-002",
      provider: "fal",
      phase: "provider_request",
      queued: true,
      queuePosition: 12,
      durationMs: 500,
      totalDurationMs: 3200,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-12",
    logName: "projects/sample-project/logs/stderr",
    timestamp: "2026-03-11T10:15:20.400Z",
    severity: "WARNING",
    jsonPayload: {
      message: "fal queue timed out in IN_QUEUE",
      toolFlow: "image_asset_generate",
      operationId: "image-op-002",
      requestId: "fal-req-002",
      provider: "fal",
      phase: "queue_wait",
      durationMs: 17200,
      totalDurationMs: 20400,
      errorMessage: "FalQueueTimeoutError",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-13",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:30:00.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Variation requested",
      toolFlow: "image_variation_generate",
      operationId: "variation-op-003",
      provider: "google",
      model: "imagen-4",
      phase: "request",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-14",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:30:02.900Z",
    severity: "WARNING",
    jsonPayload: {
      message: "Primary model failed; starting fallback",
      toolFlow: "image_variation_generate",
      operationId: "variation-op-003",
      provider: "fal",
      phase: "fallback",
      fallbackFromModel: "imagen-4",
      totalDurationMs: 2900,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-15",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:30:03.100Z",
    severity: "INFO",
    jsonPayload: {
      message: "Variation generation started",
      toolFlow: "image_variation_generate",
      operationId: "variation-op-003",
      requestId: "fal-req-003",
      provider: "fal",
      modelPath: "fal-ai/fast-sdxl",
      phase: "provider_request",
      totalDurationMs: 3100,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-16",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:30:03.500Z",
    severity: "INFO",
    jsonPayload: {
      message: "fal queue accepted",
      toolFlow: "image_variation_generate",
      operationId: "variation-op-003",
      requestId: "fal-req-003",
      provider: "fal",
      phase: "provider_request",
      queued: true,
      queuePosition: 4,
      durationMs: 700,
      totalDurationMs: 3500,
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-17",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:31:03.800Z",
    severity: "INFO",
    jsonPayload: {
      message: "fal queue still running; handing off to status polling",
      toolFlow: "image_variation_generate",
      operationId: "variation-op-003",
      requestId: "fal-req-003",
      provider: "fal",
      phase: "queue_wait",
      durationMs: 60300,
      totalDurationMs: 63800,
      status: "handed_off",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-18",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:32:05.000Z",
    severity: "INFO",
    textPayload: "[ImageVariation] Status tool called",
    jsonPayload: {
      requestId: "fal-req-003",
      provider: "fal",
      phase: "status",
    },
    resource: baseResource,
    trace: "projects/sample-project/traces/variation-trace-003",
    source: "cloud_logging_api",
  },
  {
    id: "sample-19",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:32:06.200Z",
    severity: "INFO",
    textPayload: "[ImageVariation] Status tool completed",
    jsonPayload: {
      requestId: "fal-req-003",
      provider: "fal",
      phase: "status",
      status: "COMPLETED",
      durationMs: 1200,
    },
    resource: baseResource,
    trace: "projects/sample-project/traces/variation-trace-003",
    source: "cloud_logging_api",
  },
  {
    id: "sample-20",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:32:06.500Z",
    severity: "INFO",
    textPayload: "[ImageVariation] Result tool called",
    jsonPayload: {
      requestId: "fal-req-003",
      provider: "fal",
      phase: "result",
    },
    resource: baseResource,
    trace: "projects/sample-project/traces/variation-trace-003",
    source: "cloud_logging_api",
  },
  {
    id: "sample-21",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T11:32:07.100Z",
    severity: "INFO",
    textPayload: "[ImageVariation] Result tool completed",
    jsonPayload: {
      requestId: "fal-req-003",
      provider: "fal",
      phase: "result",
      status: "COMPLETED",
      url: "https://example.com/generated/variation-op-003.png",
      durationMs: 600,
      totalDurationMs: 67100,
    },
    resource: baseResource,
    trace: "projects/sample-project/traces/variation-trace-003",
    source: "cloud_logging_api",
  },
  {
    id: "sample-22",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:00.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet variation requested",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      provider: "google",
      model: "imagen-4",
      phase: "request",
      rows: 8,
      cols: 8,
      referenceType: "static",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-23",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:00.300Z",
    severity: "INFO",
    jsonPayload: {
      message: "Provider request started",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      provider: "google",
      model: "imagen-4",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-24",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:21.000Z",
    severity: "INFO",
    jsonPayload: {
      message: "Provider request completed",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      provider: "google",
      durationMs: 20700,
      totalDurationMs: 21000,
      referenceType: "static",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-25",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:21.150Z",
    severity: "INFO",
    jsonPayload: {
      message: "Background removal completed",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      phase: "post_processing",
      durationMs: 150,
      totalDurationMs: 21150,
      referenceType: "static",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-26",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:23.100Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet upload completed",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      phase: "upload",
      durationMs: 1900,
      totalDurationMs: 23100,
      referenceType: "static",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
  {
    id: "sample-27",
    logName: "projects/sample-project/logs/stdout",
    timestamp: "2026-03-11T12:45:23.150Z",
    severity: "INFO",
    jsonPayload: {
      message: "Spritesheet variation completed",
      toolFlow: "spritesheet_variation_generate",
      operationId: "sprite-var-op-004",
      phase: "completed",
      totalDurationMs: 23150,
      referenceType: "static",
    },
    resource: baseResource,
    source: "cloud_logging_api",
  },
];
